### ISSUE TITLE
我折腾了这台机器的oc0.6.0，还差电池问题

### ISSUE THREAD

**Issue by GuaiYiHu** [Z39/Lenovo-Rescuer-14isk-15isk-Haswell-OS-X-Clover-Hotpatch#2]
您好，我是拯救者14ISE的使用者，最近折腾了这台机器的opencore0.6.0，除了电池，其他部件例如HDMI视频/音频，触控板，睡眠唤醒，声卡，显卡等全部工作了，并且顺利引导并开机了macos11.0。
这个电池在clover下是用dsdt驱动的，但是我能力有限，没法把它提炼成ssdt的形式，请问大佬愿意帮忙或者有兴趣一起继续维护这台机器呢，我可以帮忙测试。
如果愿意的话，我很快会把我做的opencore推到GitHub上
![MVIMG_20200816_203831](https://user-images.githubusercontent.com/17136448/90340080-332b2280-e028-11ea-9a44-c10d42acd5f1.jpg)

**Comment by GuaiYiHu** [comment]
没事了。

**Comment by Z39** [comment]
我已经根据你的oc做了些修改，可兼容引导win。关于电池的话，我也搞不定。当然具体我就没测试了，没有实机。

**Comment by GuaiYiHu** [comment]
我的OC已经全部搞定了，全硬件都work。

**Comment by GuaiYiHu** [comment]
“做了些修改”，这就是你拿我做好的oc打包捐赠二维码的原因？

**Comment by Z39** [comment]
这个机型的附件，无论是oc还是clover都是开放的，也根本没人会打赏的

**Comment by Z39** [comment]
其实真正就用了一个电池补丁，其他的你可以看看我们之间配的区别

**Comment by Z39** [comment]
这个机型还是得要靠你们有实机的维护下去，这个机子我就没维护，哈哈
